# Usa una imagen base para Node (etapa de build)
FROM node:18 AS build
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

# Usa una imagen base para servir archivos estáticos
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
