#version: '3.8'

services:
  mongo:
    image: mongo
    container_name: tasksdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://tasksdb:27017/mydatabase
    volumes:
      - .:/app

  frontend:
    build:
      context: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:


